### PR TITLE
Replace activesupport with corefines

### PR DESCRIPTION
**Pull request by jirutka**
Refinements FTW! :smile_cat:

### CODE REVIEW

**Comment by jirutka** [comment]
Grrr, you should really fix the tests on CI… It passes both on my machine and Travis (see [here](https://travis-ci.org/cvut/kosapi_client.rb/builds/62813534)).

**Comment by jnv** [comment]
Rejoice, for I have removed the wicked Semaphore CI's hook! It will bother us no more!

**Comment by jirutka** [comment]
:clap: :+1:

**Comment by jirutka** [comment]
And what about merging this little PR of mine? :cat:

**Comment by jnv** [comment]
Can you update corefines version and rebase?

**Comment by jirutka** [comment]
It’s IMHO not needed to update corefines, we are not using any newer refinements here.
I’ve rebased it.

**Comment by jnv** [comment]
I have no idea why this is failing but I'd suspect an auth server.

**Pull request merged**
